apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  namespace: torrentbox
  labels:
    app: sabnzbd
spec:
  type: NodePort # Expose externally via node IP and a high port
  selector:
    app: sabnzbd # Selects the Pods managed by the sabnzbd Deployment
  ports:
    - name: webui
      port: 5052 # External port from compose file
      targetPort: webui # Target the named port (8080) on the Sabnzbd container
      protocol: TCP
      # nodePort: 30052 # Optional: Specify a fixed NodePort
